"""initialize dfs

Revision ID: 80760843eebc
Revises: 
Create Date: 2022-01-21 00:20:08.119648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80760843eebc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('slate',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('slate_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('sport', sa.Integer(), nullable=True),
    sa.Column('slate_type', sa.Integer(), nullable=True),
    sa.Column('slate_type_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('slate_id')
    )
    op.create_table('contest',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.String(), nullable=False),
    sa.Column('slate_fk', sa.String(), nullable=False),
    sa.Column('prize_pool', sa.Integer(), nullable=True),
    sa.Column('max_entries', sa.Integer(), nullable=True),
    sa.Column('max_entries_per_user', sa.Integer(), nullable=True),
    sa.Column('entry_fee', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['slate_fk'], ['slate.slate_id'], ),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('contest_id')
    )
    op.create_table('entry',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('contest_fk', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('points', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['contest_fk'], ['contest.contest_id'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('playerownership',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('slate_player_id', sa.String(), nullable=False),
    sa.Column('player_fk', sa.String(), nullable=False),
    sa.Column('contest_fk', sa.String(), nullable=False),
    sa.Column('salary', sa.Numeric(), nullable=True),
    sa.Column('projected_fantasy_points', sa.Numeric(), nullable=True),
    sa.Column('actual_fantasy_points', sa.Numeric(), nullable=True),
    sa.Column('projected_ownership', sa.Numeric(), nullable=True),
    sa.Column('actual_ownership', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['contest_fk'], ['contest.contest_id'], ),
    sa.ForeignKeyConstraint(['player_fk'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('lineup',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('entry_fk', sa.String(), nullable=False),
    sa.Column('playerownership_fk', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entry_fk'], ['entry.entry_id'], ),
    sa.ForeignKeyConstraint(['playerownership_fk'], ['playerownership.slate_player_id'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineup')
    op.drop_table('playerownership')
    op.drop_table('entry')
    op.drop_table('contest')
    op.drop_table('slate')
    op.drop_table('player')
    # ### end Alembic commands ###
