"""initialize_dfs

Revision ID: 8b530f9cc942
Revises: 
Create Date: 2021-10-06 00:05:18.602321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b530f9cc942'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('slate',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('slate_id', sa.String(), nullable=False),
    sa.Column('slate_draftgroup_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('sport', sa.Integer(), nullable=True),
    sa.Column('slate_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('slate_draftgroup_id'),
    sa.UniqueConstraint('slate_id')
    )
    op.create_table('contest',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('max_entries_per_user', sa.Integer(), nullable=True),
    sa.Column('max_entries', sa.Integer(), nullable=True),
    sa.Column('total_entries', sa.Integer(), nullable=True),
    sa.Column('slate_fk', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['slate_fk'], ['slate.slate_id'], ),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('contest_id')
    )
    op.create_table('draftgroup',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Numeric(), nullable=True),
    sa.Column('draftable_id', sa.BigInteger(), nullable=True),
    sa.Column('average_fantasy_points', sa.Numeric(), nullable=True),
    sa.Column('projected_fantasy_points', sa.Numeric(), nullable=True),
    sa.Column('slate_draftgroup_fk', sa.Integer(), nullable=True),
    sa.Column('player_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_fk'], ['player.player_id'], ),
    sa.ForeignKeyConstraint(['slate_draftgroup_fk'], ['contest.contest_id'], ),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('draftable_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draftgroup')
    op.drop_table('contest')
    op.drop_table('slate')
    op.drop_table('player')
    # ### end Alembic commands ###
